### ISSUE TITLE
Finalize Typeface name!

### ISSUE THREAD

**Issue by tphinney** [tphinney/bank-gothic#8]
We need a name. Some candidates include:

- Bank Gothic Libre (nope, see discussion)
- Libre Bank Gothic (no, see discussion)

(Discussing more offline)

**Comment by kateliev** [comment]
It should be "Bank Gothic" related. In case there is no copyright infringement this makes a strong and positive association with the original. "Any other name" will result the font being "just another clone".

**Comment by tphinney** [comment]
There are several conflicting claims for a trademark on “Bank Gothic,” unfortunately. That may be an issue that leads us toward something else.

**Comment by tphinney** [comment]
OK, apparently the current (US) trademark owner for “Bank Gothic” as a typeface name is Mark Solsburg through Grosse Pointe Group LLC, and/or its subsidiary Group Type. 
(See Dan Reynolds comment of August 5, 2019 at https://typedrawers.com/discussion/3279/bank-gothic-variable-font-fontlab-vi)

So, we need a different name.

**Comment by tphinney** [comment]
Name chosen, working on trademark application.

**Comment by tphinney** [comment]
Trademark applied for! Science Gothic. USPTO application serial number 88568377
